export const Fonts = {
  Montserrat_thin: 'Montserrat-thin',
  Montserrat_extra_light: 'Montserrat-extralight',
  Montserrat_light: 'Montserrat-light',
  Montserrat_regular: 'Montserrat-regular',
  Montserrat_medium: 'Montserrat-medium',
  Montserrat_semibold: 'Montserrat-semibold',
  Montserrat_bold: 'Montserrat-bold',
  Nunito_extra_light: 'Nunito-ExtraLight',
  Nunito_light: 'Nunito-Light',
  Nunito_regular: 'Nunito-Regular',
  Nunito_medium: 'Nunito-Medium',
  Nunito_semibold: 'Nunito-SemiBold',
  Nunito_bold: 'Nunito-Bold',
};
